[package]
name = "FinSc-Thermodynamics-Wiki"
version = "0.1.0"
ipkg = "FinSc-Thermodynamics-Wiki.ipkg"

[custom.all.FinSc-Multiset-Core]
type = "local"
path = "../FinSc-Multiset-Core"
ipkg = "FinSc-Multiset-Core.ipkg"

[custom.all.FinSc-Multiset-Transform]
type = "local"
path = "../FinSc-Multiset-Transform"
ipkg = "FinSc-Multiset-Transform.ipkg"

[custom.all.FinSc-Thermodynamics]
type = "local"
path = "../FinSc-Thermodynamics"
ipkg = "FinSc-Thermodynamics.ipkg"

[custom.all.idris2-QuickCheck]
type = "local"
path = "../idris2-QuickCheck"
ipkg = "idris2-QuickCheck.ipkg"
